import { useState, useMemo, useRef, useEffect } from "react";
import { format, addWeeks } from "date-fns";
import { AnimatePresence, motion } from "framer-motion";
import { Download, Sparkles, Loader2, Minus, Plus, X, ChevronLeft, ChevronRight, Share2, Check } from "lucide-react";
import { Layout } from "@/components/layout";
import { PlanPreview } from "@/components/plan-preview";
import { ResourceEffortsPanel, type ResourceRowExport } from "@/components/resource-efforts";
import { MODELS, TRANSITION_PATHS, PHASES_META, cn } from "@/lib/utils";
import {
  useGeneratePlan,
  useDownloadPlan,
  GeneratePlanRequestTransitionPath,
  GeneratePlanResponse,
} from "@workspace/api-client-react";
import { useToast } from "@/hooks/use-toast";

// ── Disclaimers modal ──────────────────────────────────────────────────────
function DisclaimersModal({ open, onClose }: { open: boolean; onClose: () => void }) {
  if (!open) return null;
  const clauses = [
    {
      title: "1. No Warranty - Accuracy of AI-Generated Outputs",
      text: "The project plans, effort estimates, activity listings, and associated deliverables generated by 3B Michimap are produced in whole or in part by artificial intelligence language models. Such outputs are provided on an \"as is\" and \"as available\" basis without any warranty of any kind, whether express, implied, statutory, or otherwise, including but not limited to warranties of accuracy, completeness, fitness for a particular purpose, or non-infringement. The tool makes no representation that any AI-generated content reflects the actual effort, timeline, or resource requirements of any specific SAP S/4HANA engagement.",
    },
    {
      title: "2. No Commercial Reliance",
      text: "Outputs generated by this tool are strictly for internal pre-sales planning and estimation purposes. They shall not be submitted to clients, incorporated into binding commercial proposals, statements of work, or contracts without prior independent review and validation by a qualified SAP professional. The tool operator expressly disclaims all liability for any loss, damage, or claim arising from reliance on AI-generated outputs in any commercial or contractual context.",
    },
    {
      title: "3. Acceptable Use Policy",
      text: "By accessing and using 3B Michimap, you represent and warrant that: (a) you are an SAP pre-sales or delivery professional using this tool solely for internal planning purposes; (b) you will not use this tool to generate outputs intended to deceive, mislead, or defraud any third party; (c) you will not reverse-engineer, scrape, reproduce, redistribute, resell, or sublicense any portion of the tool, its underlying technology, or its generated outputs for commercial gain; (d) you will not use this tool in any manner that violates applicable law, regulation, or third-party rights; (e) you acknowledge that AI systems may produce plausible-sounding but factually incorrect content (commonly known as \"hallucinations\") and you accept full responsibility for verifying the accuracy of all outputs before use. The operator reserves the right to suspend or terminate access for any user found to be in breach of these terms.",
    },
    {
      title: "4. AI Limitations Acknowledgement",
      text: "Artificial intelligence language models used to generate content within this tool have inherent limitations: they may produce inaccurate, outdated, inconsistent, or contextually inappropriate outputs. Specifically, AI-generated SAP Activate activities, effort estimates, and resource allocations may not reflect the latest SAP methodology guidance, regional compliance requirements, or client-specific constraints. Users must apply professional judgement and independent validation to all outputs. This tool does not replace the expertise of a qualified SAP consultant.",
    },
    {
      title: "5. Data & Privacy",
      text: "Usage metadata (transition path, AI model selected, total weeks, device type, and approximate location derived from IP address) is collected for the sole purpose of product improvement and usage analytics. No personally identifiable information is required to use the core planning functionality of this tool. By using this tool you consent to the collection of this anonymised usage data.",
    },
    {
      title: "6. Intellectual Property",
      text: "SAP, SAP Activate, SAP Cloud ALM, and S/4HANA are trademarks or registered trademarks of SAP SE in Germany and other countries. This tool is an independent community resource and is not affiliated with, endorsed by, or sponsored by SAP SE. Generated outputs may incorporate publicly available SAP methodology frameworks for illustrative purposes only.",
    },
  ];
  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-black/50 backdrop-blur-sm" onClick={onClose}>
      <div className="bg-card rounded-2xl shadow-2xl max-w-2xl w-full max-h-[90vh] overflow-y-auto p-8 relative" onClick={e => e.stopPropagation()}>
        <button onClick={onClose} className="absolute top-4 right-4 p-2 rounded-full hover:bg-muted transition-colors">
          <X className="w-5 h-5 text-muted-foreground" />
        </button>
        <h2 className="text-2xl font-bold text-foreground mb-1">Disclaimers &amp; Terms of Use</h2>
        <p className="text-xs text-muted-foreground mb-6">Effective date: March 2026 · 3B Michimap</p>
        <div className="space-y-5">
          {clauses.map(d => (
            <div key={d.title} className="border-l-2 border-primary/40 pl-4">
              <h3 className="font-bold text-foreground mb-1 text-sm">{d.title}</h3>
              <p className="text-xs text-muted-foreground leading-relaxed">{d.text}</p>
            </div>
          ))}
        </div>
        <button onClick={onClose} className="mt-8 w-full bg-secondary text-secondary-foreground font-semibold rounded-xl py-3 hover:opacity-90 transition-opacity">
          Close
        </button>
      </div>
    </div>
  );
}

// ── Inline calendar picker ─────────────────────────────────────────────────
const MONTHS = ["January","February","March","April","May","June","July","August","September","October","November","December"];
const DAYS = ["Su","Mo","Tu","We","Th","Fr","Sa"];

function CalendarPicker({ value, onChange }: { value: string; onChange: (v: string) => void }) {
  const selected = value ? new Date(value + "T12:00:00") : new Date();
  const [view, setView] = useState({ year: selected.getFullYear(), month: selected.getMonth() });

  const daysInMonth = new Date(view.year, view.month + 1, 0).getDate();
  const firstDay = new Date(view.year, view.month, 1).getDay();

  const prevYear  = () => setView(v => ({ ...v, year: v.year - 1 }));
  const nextYear  = () => setView(v => ({ ...v, year: v.year + 1 }));
  const prevMonth = () => setView(v => v.month === 0 ? { year: v.year - 1, month: 11 } : { ...v, month: v.month - 1 });
  const nextMonth = () => setView(v => v.month === 11 ? { year: v.year + 1, month: 0 } : { ...v, month: v.month + 1 });

  const selectDay = (day: number) => {
    const d = new Date(view.year, view.month, day);
    onChange(format(d, "yyyy-MM-dd"));
  };

  const isSelected = (day: number) => {
    if (!value) return false;
    const s = new Date(value + "T12:00:00");
    return s.getFullYear() === view.year && s.getMonth() === view.month && s.getDate() === day;
  };

  const isToday = (day: number) => {
    const t = new Date();
    return t.getFullYear() === view.year && t.getMonth() === view.month && t.getDate() === day;
  };

  const cells = [];
  for (let i = 0; i < firstDay; i++) cells.push(null);
  for (let i = 1; i <= daysInMonth; i++) cells.push(i);

  return (
    <div className="bg-background border border-border rounded-xl p-3 w-full select-none">
      <div className="flex items-center justify-between mb-1">
        <div className="flex items-center gap-0.5">
          <button onClick={prevYear} title="Previous year" className="w-6 h-6 flex items-center justify-center rounded hover:bg-muted transition-colors text-muted-foreground hover:text-foreground">
            <ChevronLeft className="w-3 h-3" /><ChevronLeft className="w-3 h-3 -ml-2" />
          </button>
          <button onClick={prevMonth} title="Previous month" className="w-7 h-7 flex items-center justify-center rounded-lg hover:bg-muted transition-colors">
            <ChevronLeft className="w-4 h-4" />
          </button>
        </div>
        <span className="text-sm font-semibold text-foreground">{MONTHS[view.month]} {view.year}</span>
        <div className="flex items-center gap-0.5">
          <button onClick={nextMonth} title="Next month" className="w-7 h-7 flex items-center justify-center rounded-lg hover:bg-muted transition-colors">
            <ChevronRight className="w-4 h-4" />
          </button>
          <button onClick={nextYear} title="Next year" className="w-6 h-6 flex items-center justify-center rounded hover:bg-muted transition-colors text-muted-foreground hover:text-foreground">
            <ChevronRight className="w-3 h-3" /><ChevronRight className="w-3 h-3 -ml-2" />
          </button>
        </div>
      </div>
      <div className="grid grid-cols-7 mb-1">
        {DAYS.map(d => <div key={d} className="text-center text-[10px] font-bold text-muted-foreground py-1">{d}</div>)}
      </div>
      <div className="grid grid-cols-7 gap-y-0.5">
        {cells.map((day, i) => (
          <div key={i} className="flex items-center justify-center">
            {day ? (
              <button
                onClick={() => selectDay(day)}
                className={cn(
                  "w-7 h-7 rounded-full text-xs font-medium transition-colors",
                  isSelected(day) ? "bg-green-600 text-white" :
                  isToday(day) ? "font-bold text-foreground" :
                  "hover:bg-muted text-foreground"
                )}
              >
                {day}
              </button>
            ) : null}
          </div>
        ))}
      </div>
    </div>
  );
}

// ── Transition path colours ────────────────────────────────────────────────
const PATH_COLORS = {
  greenfield: { selected: "border-[#2E7D32] bg-[#E8F5E9]", title: "text-[#2E7D32]", subtitle: "text-[#388E3C]", desc: "bg-[#F1F8E9] border-[#C5E1A5]", descLabel: "text-[#558B2F]", descText: "text-[#33691E]" },
  brownfield:  { selected: "border-[#8D4E2B] bg-[#FBE9E7]", title: "text-[#6D3B20]", subtitle: "text-[#8D4E2B]", desc: "bg-[#FFF8F5] border-[#FFCCBC]", descLabel: "text-[#8D4E2B]",  descText: "text-[#5D2E14]" },
  bluefield:   { selected: "border-[#1565C0] bg-[#E3F2FD]", title: "text-[#1565C0]", subtitle: "text-[#1976D2]", desc: "bg-[#EFF8FF] border-[#BBDEFB]", descLabel: "text-[#1565C0]",  descText: "text-[#0D3C7A]" },
};

// ── Left sidebar: animated phase timeline ─────────────────────────────────
function PhaseTimeline({ phases, transitionPath }: { phases: Record<string, any>; transitionPath: string }) {
  const list = Object.entries(phases).filter(([k, v]) => k !== "discover" || v.included);
  const total = list.reduce((s, [, v]) => s + v.weeks, 0) || 1;
  const BAR_COLORS: Record<string, string> = {
    discover: "#60A5FA", prepare: "#34D399", explore: "#FB923C",
    realizeDevelop: "#FBBF24", realizeUat: "#F87171", deploy: "#14B8A6", run: "#A78BFA",
  };
  const tips: Record<string, Record<string, string>> = {
    greenfield: { discover: "Showcase SAP Best Practices demos", prepare: "Define global enterprise structure", explore: "Run FTS workshops with process owners", realizeDevelop: "Build configuration + custom ABAP", realizeUat: "Business UAT, training, rehearsals", deploy: "Production cutover and go-live", run: "Hypercare and stabilisation" },
    brownfield: { discover: "Run Readiness Check and Simplification analysis", prepare: "Set up SUM and conversion tools", explore: "Delta design for simplified processes", realizeDevelop: "Custom code remediation and trial conversions", realizeUat: "Regression UAT, end-user training", deploy: "Production system conversion", run: "Hypercare post-conversion" },
    bluefield:  { discover: "Scope selective migration objects", prepare: "Shell conversion and tool setup", explore: "Design new vs retained processes", realizeDevelop: "Selective data migration development", realizeUat: "Data validation UAT and training", deploy: "Final selective migration and go-live", run: "Data quality validation and hypercare" },
  };
  const pathTips = tips[transitionPath] || tips.greenfield;

  return (
    <div className="flex flex-col gap-2">
      <p className="text-[10px] font-bold uppercase tracking-widest text-muted-foreground mb-1">Phase Timeline</p>
      {list.map(([key, val]) => {
        const meta = PHASES_META[key];
        const pct = Math.round((val.weeks / total) * 100);
        return (
          <div key={key} className="group">
            <div className="flex items-center gap-2 mb-1">
              <span className="text-xs font-semibold text-foreground truncate flex-1">{meta?.label || key}</span>
              <span className="text-[10px] text-muted-foreground tabular-nums">{val.weeks}w</span>
            </div>
            <div className="h-2 bg-muted rounded-full overflow-hidden">
              <motion.div
                className="h-full rounded-full"
                style={{ backgroundColor: BAR_COLORS[key] || "#E9A944" }}
                initial={{ width: 0 }}
                animate={{ width: `${pct}%` }}
                transition={{ duration: 0.4, ease: "easeOut" }}
              />
            </div>
            <p className="text-[10px] text-muted-foreground mt-1 leading-snug opacity-0 group-hover:opacity-100 transition-opacity">
              {pathTips[key] || ""}
            </p>
          </div>
        );
      })}
    </div>
  );
}

// ── Right sidebar: live summary ────────────────────────────────────────────
function LiveSummary({ phases, projectStartDate, transitionPath }: { phases: Record<string, any>; projectStartDate: string; transitionPath: string }) {
  const list = Object.entries(phases).filter(([k, v]) => k !== "discover" || v.included);
  const total = list.reduce((s, [, v]) => s + v.weeks, 0);
  const months = (total / 4.33).toFixed(1);

  const hasStart = Boolean(projectStartDate);
  const startDate = hasStart ? new Date(projectStartDate + "T12:00:00") : null;
  const runWeeks  = (phases.run?.weeks ?? 0);
  const goLiveDate   = startDate ? addWeeks(startDate, total - runWeeks) : null;
  const endOfRunDate = startDate ? addWeeks(startDate, total) : null;

  const fmt = (d: Date | null) => d ? format(d, "d MMM yyyy") : "--";

  const PATH_LABEL: Record<string, string> = { greenfield: "Greenfield", brownfield: "Brownfield", bluefield: "Bluefield (SDT)" };

  return (
    <div className="space-y-4">
      <p className="text-[10px] font-bold uppercase tracking-widest text-muted-foreground">Project Summary</p>

      <div className="bg-primary/10 border border-primary/20 rounded-xl p-3 text-center">
        <p className="text-2xl font-extrabold text-primary tabular-nums">{total}</p>
        <p className="text-xs text-muted-foreground font-medium">weeks total</p>
        <p className="text-[11px] text-foreground font-semibold mt-0.5">{months} months</p>
      </div>

      <div className="space-y-2">
        <div className="flex justify-between items-center text-xs">
          <span className="text-muted-foreground">Start</span>
          <span className="font-semibold text-foreground">{fmt(startDate)}</span>
        </div>
        <div className="flex justify-between items-center text-xs">
          <span className="text-muted-foreground">Est. Go-live</span>
          <span className="font-semibold text-primary">{fmt(goLiveDate)}</span>
        </div>
        <div className="flex justify-between items-center text-xs">
          <span className="text-muted-foreground">End of Run</span>
          <span className="font-semibold text-foreground">{fmt(endOfRunDate)}</span>
        </div>
        <div className="flex justify-between items-center text-xs">
          <span className="text-muted-foreground">Approach</span>
          <span className="font-semibold text-foreground">{PATH_LABEL[transitionPath]}</span>
        </div>
        <div className="flex justify-between items-center text-xs">
          <span className="text-muted-foreground">Phases</span>
          <span className="font-semibold text-foreground">{list.length}</span>
        </div>
      </div>

      <div className="border-t border-border pt-3">
        <p className="text-[10px] font-bold uppercase tracking-widest text-muted-foreground mb-2">Phase Breakdown</p>
        <div className="space-y-1.5">
          {list.map(([key, val]) => {
            const meta = PHASES_META[key];
            const pct = Math.round((val.weeks / (total || 1)) * 100);
            return (
              <div key={key} className="flex items-center gap-2 text-xs">
                <span className={cn("w-2 h-2 rounded-full flex-shrink-0", meta?.color || "bg-gray-400")} />
                <span className="text-muted-foreground flex-1 truncate">{meta?.label || key}</span>
                <span className="font-mono font-semibold text-foreground">{val.weeks}w</span>
                <span className="text-muted-foreground w-7 text-right">{pct}%</span>
              </div>
            );
          })}
        </div>
        <div className="flex justify-between items-center text-xs border-t border-border mt-2 pt-2">
          <span className="text-muted-foreground font-semibold">Total</span>
          <span className="font-mono font-bold text-foreground">{total}w</span>
        </div>
      </div>
    </div>
  );
}

// ── Main page ──────────────────────────────────────────────────────────────
export default function Home() {
  const { mutateAsync: generatePlan } = useGeneratePlan();
  const { mutateAsync: downloadPlan, isPending: isDownloading } = useDownloadPlan();
  const { toast } = useToast();

  const [aiModel, setAiModel] = useState("gpt-5-mini");
  const [apiKey, setApiKey] = useState("");
  const [transitionPath, setTransitionPath] = useState<GeneratePlanRequestTransitionPath | null>(null);
  const [projectStartDate, setProjectStartDate] = useState("");

  const [phases, setPhases] = useState({
    discover:       { weeks: 0, included: false },
    prepare:        { weeks: 0 },
    explore:        { weeks: 0 },
    realizeDevelop: { weeks: 0 },
    realizeUat:     { weeks: 0 },
    deploy:         { weeks: 0 },
    run:            { weeks: 0 },
  });

  const [generatedResult, setGeneratedResult] = useState<GeneratePlanResponse | null>(null);
  const [showEfforts, setShowEfforts] = useState(false);
  const [confirmedEfforts, setConfirmedEfforts] = useState(false);
  const [isDisclaimersOpen, setIsDisclaimersOpen] = useState(false);
  const [agreedToTerms, setAgreedToTerms] = useState(false);
  const [hasDownloaded, setHasDownloaded] = useState(false);
  const [hasPlanDownloaded, setHasPlanDownloaded] = useState(false);
  const [ganttRows, setGanttRows] = useState<ResourceRowExport[]>([]);
  const [isGenerating, setIsGenerating] = useState(false);
  const stopRef = useRef(false);
  const [genProgress, setGenProgress] = useState(0);
  const [genStartTime, setGenStartTime] = useState<number | null>(null);
  const [genMsgIdx, setGenMsgIdx] = useState(0);

  const GEN_MESSAGES = [
    "Analyzing your SAP landscape...",
    "Mapping SAP Activate phases...",
    "Structuring activities and milestones...",
    "Calibrating effort estimates...",
    "Building resource allocation model...",
    "Preparing Gantt and workplan...",
    "Validating transition approach...",
    "Finalising your project plan...",
  ];
  const ESTIMATED_MS = 35_000;

  useEffect(() => {
    if (isGenerating) {
      setGenStartTime(Date.now());
      setGenProgress(0);
      setGenMsgIdx(0);
    } else {
      setGenStartTime(null);
    }
  }, [isGenerating]);

  useEffect(() => {
    if (!isGenerating || genStartTime === null) return;
    const tick = setInterval(() => {
      const elapsed = Date.now() - genStartTime;
      const raw = elapsed / ESTIMATED_MS;
      const pct = Math.min(94, 95 * (1 - Math.exp(-raw * 2.8)));
      setGenProgress(pct);
      const msgPct = Math.floor((elapsed / ESTIMATED_MS) * GEN_MESSAGES.length);
      setGenMsgIdx(Math.min(msgPct, GEN_MESSAGES.length - 1));
    }, 120);
    return () => clearInterval(tick);
  }, [isGenerating, genStartTime]);

  const selectPath = (path: GeneratePlanRequestTransitionPath) => {
    setTransitionPath(path);
    setGeneratedResult(null);
    setShowEfforts(false);
    setConfirmedEfforts(false);
    setAgreedToTerms(false);
    setHasDownloaded(false);
    setHasPlanDownloaded(false);
  };



  const isPaidModel = MODELS.paid.some(m => m.id === aiModel);

  const totalWeeks = useMemo(() => {
    return Object.entries(phases).reduce((s, [k, v]) => {
      if (k === "discover" && !v.included) return s;
      return s + v.weeks;
    }, 0);
  }, [phases]);

  const updatePhaseWeeks = (key: keyof typeof phases, delta: number) => {
    setPhases(prev => ({ ...prev, [key]: { ...prev[key], weeks: Math.max(0, prev[key].weeks + delta) } }));
  };

  const setPhaseWeeks = (key: keyof typeof phases, raw: string) => {
    const val = parseInt(raw, 10);
    setPhases(prev => ({ ...prev, [key]: { ...prev[key], weeks: isNaN(val) || val < 0 ? 0 : val } }));
  };

  const handleStop = () => {
    stopRef.current = true;
    setIsGenerating(false);
  };

  const handleGenerate = async () => {
    if (!transitionPath) {
      toast({ title: "Transition Path Required", description: "Please select a transition path before generating.", variant: "destructive" });
      return;
    }
    if (isPaidModel && !apiKey.trim()) {
      toast({ title: "API Key Required", description: "Please enter your API key for the selected paid model.", variant: "destructive" });
      return;
    }
    stopRef.current = false;
    setHasPlanDownloaded(false);
    setHasDownloaded(false);
    setIsGenerating(true);
    try {
      const res = await generatePlan({
        data: {
          aiModel,
          apiKey: isPaidModel ? apiKey : null,
          transitionPath,
          projectStartDate,
          phases: {
            discover:       phases.discover,
            prepare:        { weeks: phases.prepare.weeks },
            explore:        { weeks: phases.explore.weeks },
            realizeDevelop: { weeks: phases.realizeDevelop.weeks },
            realizeUat:     { weeks: phases.realizeUat.weeks },
            deploy:         { weeks: phases.deploy.weeks },
            run:            { weeks: phases.run.weeks },
          },
        },
      });
      if (!stopRef.current) {
        setGeneratedResult(res);
        setTimeout(() => document.getElementById("plan-preview")?.scrollIntoView({ behavior: "smooth" }), 200);
      }
    } catch (err: any) {
      if (!stopRef.current) {
        toast({ title: "Generation Failed", description: err.message || "Failed to generate project plan.", variant: "destructive" });
      }
    } finally {
      setIsGenerating(false);
    }
  };

  const triggerDownload = (blob: Blob, filename: string) => {
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = filename;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  const handleDownloadPlanOnly = async () => {
    if (!generatedResult) return;
    try {
      const blob = await downloadPlan({ data: { planId: generatedResult.planId } as any });
      triggerDownload(blob as Blob, `3B_Michimap_Plan_${transitionPath}_${projectStartDate}.xlsx`);
      setHasPlanDownloaded(true);
      toast({ title: "Download Started", description: "Your SAP Activate project plan is downloading." });
    } catch {
      toast({ title: "Download Failed", description: "Please try again or regenerate the plan.", variant: "destructive" });
    }
  };

  const handleDownload = async () => {
    if (!generatedResult) return;
    try {
      const blob = await downloadPlan({ data: { planId: generatedResult.planId, resourceRows: ganttRows } as any });
      triggerDownload(blob as Blob, `3B_Michimap_Full_${transitionPath}_${projectStartDate}.xlsx`);
      setHasDownloaded(true);
      toast({ title: "Download Started", description: "Your full resource plan is downloading." });
    } catch {
      toast({ title: "Download Failed", description: "Please try again or regenerate the plan.", variant: "destructive" });
    }
  };

  const appUrl = "https://3bmichimap.replit.app";

  const linkedInShareUrl = `https://www.linkedin.com/sharing/share-offsite/?url=${encodeURIComponent(appUrl)}`;

  const colors = transitionPath ? PATH_COLORS[transitionPath] : null;

  return (
    <Layout>
      <DisclaimersModal open={isDisclaimersOpen} onClose={() => setIsDisclaimersOpen(false)} />

      {/* STICKY STEP INDICATOR */}
      {(() => {
        const currentStep = (showEfforts || confirmedEfforts) ? 6 : generatedResult ? 5 : (transitionPath && projectStartDate) ? 4 : transitionPath ? 3 : 2;
        const STEPS = [
          { id: 1, label: "Choose LLM"              },
          { id: 2, label: "Transition Path"          },
          { id: 3, label: "Start Date"               },
          { id: 4, label: "Enter Duration"           },
          { id: 5, label: "Generate Plan & Download" },
          { id: 6, label: "Enter Efforts & Download" },
        ];
        return (
          <div className="sticky top-14 z-40 bg-background border-b border-border shadow-sm">
            <div className="max-w-screen-xl mx-auto px-4 py-4">
              <div className="flex items-start w-full">
                {STEPS.map((step, i) => {
                  const done   = step.id < currentStep;
                  const active = step.id === currentStep;
                  return (
                    <div key={step.id} className="flex items-center flex-1 min-w-0">
                      <div className="flex flex-col items-center gap-1.5 shrink-0">
                        <div className={cn(
                          "w-9 h-9 rounded-full flex items-center justify-center text-xs font-bold border-2 transition-all duration-300",
                          done   ? "bg-green-500 border-green-500 text-white shadow-[0_0_0_3px_rgba(34,197,94,0.18)]"
                                 : active ? "border-primary text-primary bg-primary/10 shadow-[0_0_0_3px_rgba(233,169,68,0.18)]"
                                         : "border-border text-muted-foreground bg-muted/40"
                        )}>
                          {done ? <Check className="w-4 h-4 stroke-[3]" /> : step.id}
                        </div>
                        <span className={cn(
                          "text-[10px] font-semibold text-center leading-tight max-w-[60px] transition-colors duration-200",
                          active ? "text-primary" : done ? "text-green-600" : "text-muted-foreground"
                        )}>
                          {step.label}
                        </span>
                      </div>
                      {i < STEPS.length - 1 && (
                        <div className={cn(
                          "flex-1 h-1 mx-2 mb-5 transition-colors duration-300 rounded-full",
                          step.id < currentStep ? "bg-green-400" : "bg-border"
                        )} />
                      )}
                    </div>
                  );
                })}
              </div>
            </div>
          </div>
        );
      })()}

      {/* Two-column layout */}
      <div className="min-h-screen">
        <div className="max-w-screen-xl mx-auto px-4 py-8 overflow-x-clip">
          <div className="grid grid-cols-1 xl:grid-cols-[1fr_300px] gap-6 items-start">

            {/* ── CENTRE COLUMN ── */}
            <div className="space-y-6 min-w-0 overflow-x-hidden">

              {/* HERO */}
              <div className="space-y-3">
                <div className="inline-flex items-center gap-2 px-4 py-1.5 rounded-full border border-primary/30 bg-card text-primary text-sm font-medium shadow-sm">
                  <Sparkles className="w-3.5 h-3.5" />
                  AI-Powered SAP Activate Planner
                </div>

                <h1 className="text-4xl md:text-5xl font-extrabold text-foreground uppercase tracking-tight leading-[1.05]">
                  Every Implementation<br />Has A{" "}
                  <span className="text-primary relative inline-block">
                    Road.
                    <svg className="absolute w-full h-2.5 -bottom-0.5 left-0 text-primary" viewBox="0 0 100 10" preserveAspectRatio="none">
                      <path d="M0 5 Q 50 10 100 5" stroke="currentColor" strokeWidth="4" fill="none" strokeLinecap="round" />
                    </svg>
                  </span>
                </h1>

                <p className="text-base text-muted-foreground leading-relaxed">
                  <span className="text-primary font-semibold">3B Michimap</span> generates the structured estimation template to accelerate your SAP S/4HANA transformation needs.
                </p>

                <div className="flex flex-wrap gap-2 pt-1">
                  {["Greenfield", "Brownfield", "Bluefield", "SAP Activate", "S/4HANA", "Pre-sales"].map(tag => (
                    <span key={tag} className="px-3 py-1 text-xs font-medium text-foreground/60 bg-card border border-border rounded-full">
                      {tag}
                    </span>
                  ))}
                </div>
              </div>

              {/* FORM CARD */}
              <div className="bg-card rounded-2xl border border-border shadow-md overflow-hidden">
                <div className="p-6 space-y-8">

                  {/* AI MODEL */}
                  <div className="space-y-2">
                    <label className="text-xs font-bold text-primary uppercase tracking-wider">AI Model</label>
                    <div className="relative">
                      <select
                        value={aiModel}
                        onChange={e => setAiModel(e.target.value)}
                        className="w-full bg-background border border-border rounded-xl px-4 py-3 text-sm text-foreground focus:outline-none focus:ring-2 focus:ring-primary/30 focus:border-primary transition-all appearance-none pr-10 cursor-pointer"
                        style={{ backgroundImage: `url("data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' fill='none' viewBox='0 0 24 24' stroke='%23666'%3E%3Cpath stroke-linecap='round' stroke-linejoin='round' stroke-width='2' d='M19 9l-7 7-7-7'/%3E%3C/svg%3E")`, backgroundPosition: "right 0.75rem center", backgroundRepeat: "no-repeat", backgroundSize: "1.2em" }}
                      >
                        <optgroup label="Free (via Replit - No Key Needed)">
                          {MODELS.free.map(m => <option key={m.id} value={m.id}>{m.name}</option>)}
                        </optgroup>
                        <optgroup label="Paid (Enter Your API Key Below)">
                          {MODELS.paid.map(m => <option key={m.id} value={m.id}>{m.name}</option>)}
                        </optgroup>
                      </select>
                    </div>
                    <AnimatePresence>
                      {isPaidModel && (
                        <motion.div initial={{ opacity: 0, height: 0 }} animate={{ opacity: 1, height: "auto" }} exit={{ opacity: 0, height: 0 }} className="overflow-hidden">
                          <input type="password" placeholder="Enter your API key..." value={apiKey} onChange={e => setApiKey(e.target.value)}
                            className="w-full mt-2 bg-background border border-primary/40 rounded-xl px-4 py-3 text-sm text-foreground font-mono focus:outline-none focus:ring-2 focus:ring-primary/30 focus:border-primary transition-all" />
                        </motion.div>
                      )}
                    </AnimatePresence>
                  </div>

                  {/* TRANSITION PATH */}
                  <div className="space-y-3">
                    <label className="text-xs font-bold text-primary uppercase tracking-wider">Transition Path</label>
                    <div className="grid grid-cols-3 gap-3">
                      {(Object.keys(TRANSITION_PATHS) as GeneratePlanRequestTransitionPath[]).map(pathId => {
                        const path = TRANSITION_PATHS[pathId];
                        const c = PATH_COLORS[pathId];
                        const isSelected = transitionPath === pathId;
                        return (
                          <button key={pathId} onClick={() => selectPath(pathId)}
                            className={cn("text-left p-4 rounded-xl border-2 transition-all duration-200", isSelected ? c.selected : "border-border bg-background hover:border-border/80 hover:bg-muted/30")}>
                            <div className={cn("font-bold text-sm mb-1", isSelected ? c.title : "text-foreground")}>{path.name.split(" (")[0]}</div>
                            <div className={cn("text-[11px] leading-tight", isSelected ? c.subtitle : "text-muted-foreground")}>{path.subtitle}</div>
                          </button>
                        );
                      })}
                    </div>
                    {transitionPath && colors && (
                      <AnimatePresence mode="wait">
                        <motion.div key={transitionPath} initial={{ opacity: 0, y: -6 }} animate={{ opacity: 1, y: 0 }} exit={{ opacity: 0 }} transition={{ duration: 0.2 }}
                          className={cn("rounded-xl border p-4 space-y-3", colors.desc)}>
                          <div>
                            <p className={cn("text-xs font-bold uppercase tracking-wide mb-1", colors.descLabel)}>{TRANSITION_PATHS[transitionPath].name}</p>
                            <p className={cn("text-sm leading-relaxed", colors.descText)}>
                              {TRANSITION_PATHS[transitionPath].description}
                            </p>
                          </div>
                          {TRANSITION_PATHS[transitionPath].tip && (
                            <div className={cn("rounded-lg border px-3 py-2.5 flex gap-2", colors.desc)}>
                              <span className="text-base leading-none mt-0.5 shrink-0">💡</span>
                              <p className={cn("text-[11px] leading-relaxed", colors.descText)}>
                                <span className={cn("font-bold", colors.descLabel)}>Did you know? </span>
                                {TRANSITION_PATHS[transitionPath].tip}
                              </p>
                            </div>
                          )}
                        </motion.div>
                      </AnimatePresence>
                    )}
                  </div>

                  {/* PROJECT START DATE */}
                  <div className="space-y-2">
                    <label className="text-xs font-bold text-primary uppercase tracking-wider">Project Start Date</label>
                    <CalendarPicker value={projectStartDate} onChange={setProjectStartDate} />
                  </div>

                  {/* PHASE DURATIONS */}
                  <div className="space-y-3">
                    <label className="text-xs font-bold text-primary uppercase tracking-wider">Phase Durations (Weeks)</label>
                    <div className="grid grid-cols-2 gap-3">
                      {(Object.entries(phases) as [keyof typeof phases, any][]).map(([key, data]) => {
                        const meta = PHASES_META[key];
                        const isOptional = key === "discover";
                        const isIncluded = !isOptional || data.included;
                        return (
                          <div key={key} className={cn("bg-background border border-border rounded-xl p-4 transition-all", !isIncluded && "opacity-50")}>
                            <div className="flex items-start justify-between mb-1.5">
                              <div className="flex items-center gap-2">
                                <span className={cn("w-2 h-2 rounded-full flex-shrink-0", meta?.color || "bg-gray-400")} />
                                <span className="font-bold text-sm text-foreground">{meta?.label || key}</span>
                              </div>
                              {isOptional && (
                                <span className="text-[10px] font-semibold text-amber-600 bg-amber-100 px-2 py-0.5 rounded-full leading-tight">Optional</span>
                              )}
                            </div>
                            <p className="text-xs text-muted-foreground mb-3 pl-4 leading-snug">{meta?.desc}</p>
                            {isOptional && (
                              <label className="flex items-center gap-2 mb-3 pl-4 cursor-pointer">
                                <input type="checkbox" checked={data.included}
                                  onChange={() => setPhases(p => ({ ...p, discover: { ...p.discover, included: !p.discover.included } }))}
                                  className="w-3.5 h-3.5 rounded border-border text-primary cursor-pointer" />
                                <span className="text-xs text-muted-foreground">Include in plan</span>
                              </label>
                            )}
                            <div className={cn("flex items-center gap-2 justify-between", !isIncluded && "pointer-events-none")}>
                              <button onClick={() => updatePhaseWeeks(key, -1)} disabled={!isIncluded || data.weeks <= 0}
                                className="w-7 h-7 flex items-center justify-center rounded-lg border border-border bg-card hover:bg-muted transition-colors disabled:opacity-40">
                                <Minus className="w-3 h-3" />
                              </button>
                              <input
                                type="number" min={0}
                                value={data.weeks}
                                disabled={!isIncluded}
                                onChange={e => setPhaseWeeks(key, e.target.value)}
                                className="font-bold text-lg text-foreground tabular-nums w-14 text-center bg-transparent border-b-2 border-primary/30 focus:border-primary focus:outline-none disabled:opacity-40 [appearance:textfield] [&::-webkit-inner-spin-button]:appearance-none [&::-webkit-outer-spin-button]:appearance-none"
                              />
                              <button onClick={() => updatePhaseWeeks(key, 1)} disabled={!isIncluded}
                                className="w-7 h-7 flex items-center justify-center rounded-lg border border-border bg-card hover:bg-muted transition-colors disabled:opacity-40">
                                <Plus className="w-3 h-3" />
                              </button>
                              <span className="text-xs text-muted-foreground ml-1">weeks</span>
                            </div>
                          </div>
                        );
                      })}
                    </div>

                    <div className="flex items-center justify-between bg-muted/40 border border-border rounded-xl px-5 py-4 mt-2">
                      <span className="text-sm font-medium text-foreground">Total Duration</span>
                      <span className="text-base font-bold text-foreground">
                        {totalWeeks} weeks <span className="text-sm font-normal text-muted-foreground">(~{(totalWeeks / 4.33).toFixed(1)} months)</span>
                      </span>
                    </div>
                  </div>

                  {/* GENERATE / STOP BUTTON */}
                  {isGenerating ? (
                    <div className="space-y-3">
                      <button onClick={handleStop}
                        className="w-full flex items-center justify-center gap-3 bg-destructive text-destructive-foreground font-bold text-base rounded-2xl py-5 shadow-lg hover:opacity-90 active:scale-[0.99] transition-all">
                        <X className="w-5 h-5" /> Stop Generation
                      </button>
                      {/* Progress bar */}
                      <div className="space-y-2">
                        <div className="flex items-center justify-between text-xs">
                          <span className="text-muted-foreground font-medium truncate pr-2">
                            {GEN_MESSAGES[genMsgIdx]}
                          </span>
                          <span className="font-bold text-primary tabular-nums shrink-0">
                            {Math.round(genProgress)}%
                          </span>
                        </div>
                        <div className="h-2 w-full bg-muted rounded-full overflow-hidden">
                          <div
                            className="h-full rounded-full bg-primary transition-all duration-200 ease-out"
                            style={{ width: `${genProgress}%` }}
                          />
                        </div>
                        <p className="text-[11px] text-muted-foreground/70 text-center">
                          {genStartTime
                            ? `~${Math.max(0, Math.round((ESTIMATED_MS - (Date.now() - genStartTime)) / 1000))}s remaining`
                            : "Starting..."}
                        </p>
                      </div>
                    </div>
                  ) : (
                    <button onClick={handleGenerate} disabled={!transitionPath}
                      className={cn("w-full flex items-center justify-center gap-3 font-bold text-base rounded-2xl py-5 shadow-lg transition-all",
                        transitionPath
                          ? "bg-secondary text-secondary-foreground hover:opacity-90 active:scale-[0.99]"
                          : "bg-muted text-muted-foreground cursor-not-allowed opacity-60")}>
                      <Sparkles className="w-5 h-5" /> Generate Project Plan
                    </button>
                  )}
                </div>

              </div>

              {/* PLAN PREVIEW */}
              <AnimatePresence>
                {generatedResult && (
                  <motion.div id="plan-preview" initial={{ opacity: 0, y: 24 }} animate={{ opacity: 1, y: 0 }} className="mt-4 space-y-4">
                    <PlanPreview plan={generatedResult.plan} />

                    {/* STEP 5 ACTIONS: Disclaimer + Download Plan + Enter Efforts */}
                    {!showEfforts && (
                      <div className="space-y-3">
                        {/* Disclaimer checkbox */}
                        <label className="flex items-start gap-2.5 cursor-pointer group mx-auto w-fit">
                          <input
                            type="checkbox"
                            checked={agreedToTerms}
                            onChange={e => setAgreedToTerms(e.target.checked)}
                            className="mt-0.5 w-4 h-4 accent-primary shrink-0"
                          />
                          <span className="text-[12px] text-muted-foreground leading-snug">
                            I acknowledge this plan is AI-generated and for pre-sales use only.{" "}
                            <button
                              type="button"
                              onClick={() => setIsDisclaimersOpen(true)}
                              className="text-primary underline underline-offset-2 hover:opacity-80 transition-opacity font-medium">
                              Read Disclaimers
                            </button>
                          </span>
                        </label>

                        <div className="flex flex-wrap items-center justify-center gap-3">
                          <button
                            onClick={handleDownloadPlanOnly}
                            disabled={isDownloading || !agreedToTerms}
                            className={cn(
                              "flex items-center gap-2 px-6 py-3 rounded-xl font-semibold text-sm shadow transition-all",
                              !agreedToTerms
                                ? "opacity-40 cursor-not-allowed bg-foreground text-background"
                                : hasPlanDownloaded
                                  ? "bg-green-500 text-white hover:bg-green-600"
                                  : "bg-foreground text-background hover:opacity-80"
                            )}>
                            {hasPlanDownloaded
                              ? <><Check className="w-4 h-4" /> Plan Downloaded</>
                              : <><Download className="w-4 h-4" /> Download Plan (Excel)</>}
                          </button>
                          <button
                            onClick={() => {
                              setAgreedToTerms(false);
                              setShowEfforts(true);
                              setTimeout(() => document.getElementById("resource-efforts")?.scrollIntoView({ behavior: "smooth", block: "start" }), 80);
                            }}
                            className="flex items-center gap-2 px-6 py-3 rounded-xl bg-primary text-primary-foreground font-semibold text-sm shadow hover:opacity-90 transition-all">
                            <Plus className="w-4 h-4" /> Enter Resource Efforts
                          </button>
                        </div>
                      </div>
                    )}

                    {/* RESOURCE EFFORTS PANEL */}
                    <AnimatePresence>
                      {showEfforts && (
                        <motion.div id="resource-efforts"
                          initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }} exit={{ opacity: 0, y: 10 }}>
                          <div className="mb-3">
                            <h2 className="font-bold text-base text-foreground">Resource Efforts</h2>
                          </div>
                          <ResourceEffortsPanel
                            plan={generatedResult.plan}
                            agreedToTerms={agreedToTerms}
                            setAgreedToTerms={setAgreedToTerms}
                            onOpenDisclaimers={() => setIsDisclaimersOpen(true)}
                            isDownloading={isDownloading}
                            onDownload={handleDownload}
                            hasDownloaded={hasDownloaded}
                            linkedInShareUrl={linkedInShareUrl}
                            onConfirm={() => setConfirmedEfforts(true)}
                            onUnconfirm={() => setConfirmedEfforts(false)}
                            onDataChange={rows => setGanttRows(rows)}
                          />
                        </motion.div>
                      )}
                    </AnimatePresence>
                  </motion.div>
                )}
              </AnimatePresence>
            </div>

            {/* ── RIGHT SIDEBAR ── */}
            <div className="hidden xl:block sticky top-[136px] space-y-4">
              <div className="bg-card border border-border rounded-2xl p-5 shadow-sm">
                <LiveSummary phases={phases} projectStartDate={projectStartDate} transitionPath={transitionPath} />
              </div>
            </div>
          </div>
        </div>
      </div>
    </Layout>
  );
}
