import { ReactNode } from "react";
import { Link } from "wouter";
import { useGetMe } from "@workspace/api-client-react";
import { LayoutDashboard } from "lucide-react";

const APP_URL = typeof window !== "undefined" ? window.location.origin : "https://3bmichimap.replit.app";
const SHARE_TEXT = `I just generated an AI-powered SAP S/4HANA project plan in seconds using 3B Michimap - a free pre-sales planning tool built on SAP Activate. Try it → ${APP_URL} #SAP #S4HANA #SAPActivate #PreSales`;
const X_URL = `https://twitter.com/intent/tweet?text=${encodeURIComponent(SHARE_TEXT)}`;
const LI_URL = `https://www.linkedin.com/sharing/share-offsite/?url=${encodeURIComponent(APP_URL)}`;

export function Layout({ children }: { children: ReactNode }) {
  const { data: user } = useGetMe();

  return (
    <div className="min-h-screen flex flex-col bg-background">
      {/* HEADER */}
      <header className="sticky top-0 z-50 w-full bg-background border-b border-border">
        <div className="max-w-screen-xl mx-auto px-4 h-14 flex items-center justify-between">
          <Link href="/" className="flex items-center gap-2.5 hover:opacity-85 transition-opacity">
            <div className="bg-[#E9A944] text-white font-extrabold text-sm px-2.5 py-1.5 rounded-lg leading-none">
              3B
            </div>
            <div>
              <div className="font-bold text-base text-foreground leading-none">Michimap</div>
              <div className="text-[9px] uppercase tracking-widest text-muted-foreground font-medium leading-tight">
                AI-POWERED FRAMEWORK TO PLAN YOUR EFFORTS. ZERO GUESSWORK.
              </div>
            </div>
          </Link>

          <div className="flex items-center gap-3">
            {/* Share buttons - always visible */}
            <a
              href={X_URL}
              target="_blank"
              rel="noopener noreferrer"
              title="Share on X"
              className="flex items-center gap-1.5 px-3 py-1.5 rounded-lg bg-black text-white text-xs font-bold hover:bg-black/75 transition-colors"
            >
              <svg className="w-3 h-3" viewBox="0 0 24 24" fill="currentColor">
                <path d="M18.244 2.25h3.308l-7.227 8.26 8.502 11.24H16.17l-4.714-6.231-5.401 6.231H2.744l7.73-8.835L2.25 2.25h6.986l4.263 5.637L18.244 2.25zm-1.161 17.52h1.833L7.084 4.126H5.117L17.083 19.77z" />
              </svg>
              <span className="hidden sm:inline">Share</span>
            </a>
            <a
              href={LI_URL}
              target="_blank"
              rel="noopener noreferrer"
              title="Share on LinkedIn"
              className="flex items-center gap-1.5 px-3 py-1.5 rounded-lg bg-[#0A66C2] text-white text-xs font-bold hover:bg-[#0958a8] transition-colors"
            >
              <svg className="w-3 h-3" viewBox="0 0 24 24" fill="currentColor">
                <path d="M20.447 20.452h-3.554v-5.569c0-1.328-.027-3.037-1.852-3.037-1.853 0-2.136 1.445-2.136 2.939v5.667H9.351V9h3.414v1.561h.046c.477-.9 1.637-1.85 3.37-1.85 3.601 0 4.267 2.37 4.267 5.455v6.286zM5.337 7.433a2.062 2.062 0 0 1-2.063-2.065 2.064 2.064 0 1 1 2.063 2.065zm1.782 13.019H3.555V9h3.564v11.452zM22.225 0H1.771C.792 0 0 .774 0 1.729v20.542C0 23.227.792 24 1.771 24h20.451C23.2 24 24 23.227 24 22.271V1.729C24 .774 23.2 0 22.222 0h.003z" />
              </svg>
              <span className="hidden sm:inline">Share</span>
            </a>

            {user?.isAdmin && (
              <Link href="/admin" className="flex items-center gap-1.5 text-sm font-medium text-primary hover:text-primary/80 transition-colors">
                <LayoutDashboard className="w-4 h-4" />
                Admin
              </Link>
            )}
          </div>
        </div>
      </header>

      <main className="flex-1">
        {children}
      </main>

      {/* FOOTER */}
      <footer className="border-t border-border bg-background py-6 mt-6">
        <div className="max-w-screen-xl mx-auto px-4 text-center space-y-2">
          <p className="text-sm text-muted-foreground">
            Dedicated to the SAP Pre-sales community by{" "}
            <a
              href="https://www.linkedin.com/in/bharathbhushanb/"
              target="_blank"
              rel="noopener noreferrer"
              className="font-bold text-foreground hover:text-primary transition-colors underline underline-offset-2"
            >
              Bharath Bhushan Bogi Setty
            </a>.
          </p>
          <p className="text-xs text-muted-foreground/70">
            Free and open source. SAP and SAP Activate are trademarks of SAP SE.
          </p>
          <p className="text-[11px] text-muted-foreground/60 max-w-2xl mx-auto leading-relaxed border-t border-border pt-3 mt-3">
            <strong className="text-muted-foreground">AI Disclaimer:</strong> Outputs generated by this tool are produced by artificial intelligence and may contain errors, omissions, or inaccuracies. They are provided for indicative planning purposes only and do not constitute professional consulting advice. Always validate outputs with a qualified SAP professional before use in any commercial context.
          </p>
        </div>
      </footer>
    </div>
  );
}
