// @ts-nocheck
import { Resend } from "resend";
import { logger } from "./logger";

async function getResendClient(): Promise<{ client: Resend; fromEmail: string }> {
  const hostname = process.env.REPLIT_CONNECTORS_HOSTNAME;
  const xReplitToken = process.env.REPL_IDENTITY
    ? "repl " + process.env.REPL_IDENTITY
    : process.env.WEB_REPL_RENEWAL
    ? "depl " + process.env.WEB_REPL_RENEWAL
    : null;

  if (hostname && xReplitToken) {
    try {
      const data = await fetch(
        "https://" + hostname + "/api/v2/connection?include_secrets=true&connector_names=resend",
        { headers: { Accept: "application/json", "X-Replit-Token": xReplitToken } }
      ).then((r) => r.json()).then((d) => d.items?.[0]);

      if (data?.settings?.api_key) {
        return {
          client: new Resend(data.settings.api_key),
          fromEmail: data.settings.from_email || "3B Michimap <noreply@3bmichimap.com>",
        };
      }
    } catch (err) {
      logger.warn({ err }, "Failed to fetch Resend credentials from connector");
    }
  }

  const apiKey = process.env.RESEND_API_KEY;
  if (!apiKey) throw new Error("Resend not configured");
  return {
    client: new Resend(apiKey),
    fromEmail: process.env.RESEND_FROM_EMAIL || "3B Michimap <noreply@resend.dev>",
  };
}

export async function sendPlanEmail({
  to,
  name,
  transitionPath,
  totalWeeks,
  projectStartDate,
  excelBuffer,
  fileName,
}: {
  to: string;
  name?: string;
  transitionPath: string;
  totalWeeks: number;
  projectStartDate: string;
  excelBuffer: Buffer;
  fileName: string;
}): Promise<{ success: boolean; messageId?: string; error?: string }> {
  try {
    const { client, fromEmail } = await getResendClient();

    const greeting = name ? `Hi ${name},` : "Hi,";
    const pathLabel = transitionPath.charAt(0).toUpperCase() + transitionPath.slice(1);
    const months = Math.round(totalWeeks / 4.3);

    const { data, error } = await client.emails.send({
      from: fromEmail,
      to,
      subject: `Your 3B Michimap SAP Project Plan (${pathLabel})`,
      html: `
        <div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto; padding: 24px;">
          <div style="background: #E9A944; padding: 16px 24px; border-radius: 8px 8px 0 0;">
            <span style="color: white; font-size: 20px; font-weight: 900;">3B Michimap</span>
            <span style="color: rgba(255,255,255,0.8); font-size: 12px; margin-left: 8px;">SAP S/4HANA Planner</span>
          </div>
          <div style="background: #ffffff; border: 1px solid #e5e7eb; border-top: none; padding: 32px; border-radius: 0 0 8px 8px;">
            <p style="color: #111827; font-size: 16px; margin: 0 0 16px;">${greeting}</p>
            <p style="color: #374151; font-size: 14px; margin: 0 0 24px; line-height: 1.6;">
              Your <strong>${pathLabel}</strong> SAP S/4HANA project plan is ready. It covers
              <strong>${totalWeeks} weeks (~${months} months)</strong> starting from <strong>${projectStartDate}</strong>.
            </p>
            <p style="color: #374151; font-size: 14px; margin: 0 0 24px; line-height: 1.6;">
              Your plan is attached as an Excel file. It includes phase-by-phase activities, RACI assignments,
              milestones, and an executive summary generated by AI.
            </p>
            <div style="background: #FFF8E7; border-left: 4px solid #E9A944; padding: 12px 16px; border-radius: 4px; margin: 0 0 24px;">
              <p style="color: #92400e; font-size: 13px; margin: 0; font-style: italic;">
                This plan is indicative and intended for pre-sales planning purposes only.
                Please validate with a qualified SAP professional before commercial use.
              </p>
            </div>
            <p style="color: #6b7280; font-size: 12px; margin: 0;">
              Generated by 3B Michimap &mdash; Dedicated to the SAP Pre-sales community by Bharath Bhushan Bogi Setty.
            </p>
          </div>
        </div>
      `,
      attachments: [
        {
          filename: fileName,
          content: excelBuffer.toString("base64"),
        },
      ],
    });

    if (error) {
      logger.warn({ error }, "Resend returned error");
      return { success: false, error: error.message };
    }

    return { success: true, messageId: data?.id };
  } catch (err: any) {
    logger.error({ err }, "Failed to send email via Resend");
    return { success: false, error: err?.message || "Email send failed" };
  }
}
